//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loading_price.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\podma\\\\OneDrive\\\\Рабочий стол\\\\СМК РАБОТА\\\\NEW_PROG\\\\prototype - NEW F" +
            "ORMAT.xls")]
        public string path_file {
            get {
                return ((string)(this["path_file"]));
            }
            set {
                this["path_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Mebel\\\\Прототипы\\\\prototypes.db")]
        public string path_prototypes {
            get {
                return ((string)(this["path_prototypes"]));
            }
            set {
                this["path_prototypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Mebel\\\\Bin64\\\\Settings.db")]
        public string path_settings {
            get {
                return ((string)(this["path_settings"]));
            }
            set {
                this["path_settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\podma\\\\Документы\\\\logs_loading_price")]
        public string path_logs {
            get {
                return ((string)(this["path_logs"]));
            }
            set {
                this["path_logs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Mebel\\\\Текстуры")]
        public string path_textures {
            get {
                return ((string)(this["path_textures"]));
            }
            set {
                this["path_textures"] = value;
            }
        }
    }
}
